name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.16

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download model from Hugging Face
      run: |
        huggingface-cli download 2Noise/ChatTTS

    - name: Find the latest snapshot directory with hash
      id: model_path
      run: |
        # Find the latest snapshot directory (level 1 directory) by sorting the directories by modification time
        MODEL_DIR=$(ls -d ~/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/* | sort -r | head -n 1)
        echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_ENV

    - name: Archive the model with torch-model-archiver
      run: |
        torch-model-archiver --model-name chattts \
                             --version 1.0 \
                             --serialized-file ${{ env.MODEL_DIR }}/asset/Decoder.pt \
                             --handler model_handler.py \
                             --extra-files ${{ env.MODEL_DIR }} \
                             --export-path model_store
    
    - name: Build the Docker image
      uses: docker/build-push-action@v6.11.0
      with:
        context: .
        push: true
        tags: chattts-torchserve:latest
        github-token: ${{ github.token }}

